---
# Create DNS challenges for DNS provider HostTech
- name: Creating challenge DNS entries for domains {{ ', '.join(domains) }}" via HostTech API
  local_action:
    module: hosttech_dns
    state: present
    zone: "{{ item.key | regex_replace('^(?:.*\\.|)([^.]+\\.[^.]+)$', '\\1') }}"
    record: "{{ item.key }}"
    type: TXT
    ttl: 300
    value: "{{ item.value }}"
    overwrite: true
    hosttech_username: "{{ hosttech_username }}"
    hosttech_password: "{{ hosttech_password }}"
  run_once: True
  with_dict: "{{ lets_encrypt_challenge.challenge_data_dns }}"
  tags:
  - issue-tls-certs-newkey
  - issue-tls-certs
